site_name: PHY 351 Reference

theme:
  name: mkdocs
  color-mode: auto
  user_color_mode_toggle: true

plugins:
    - search
    - awesome-pages

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # Doesn't seem to work: - javascripts/shortcuts.js

extra_css:
  - css/custom.css
