site_name: PHY 351 Reference
repo_url: "https://github.com/UNCG-PHY-351-S25.github.io"

theme:
  name: mkdocs
  color-mode: auto
  user_color_mode_toggle: true
  toc_depth: 3  # Doesn't work with default theme, alas.

plugins:
    - search
    - awesome-pages
    # - myst-parser

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # Doesn't seem to work: - javascripts/shortcuts.js

extra_css:
  - css/custom.css
